from email.message import EmailMessage
import smtplib

EMAIL = "myemail@gmail.com" #your email
PASSWORD = "mypassword"      #your password
msg = EmailMessage()

msg['Subject'] = 'Email using python' #Subject
msg['From'] = EMAIL                   #Sender's email
msg['TO'] = ['mysender mail'] #Reciver email
message = "This email is generated by python"
msg.set_content(message)

attachments = [#List of attachment files"file path"
                'C:\\Users\\....' ]

for path in attachments:#Loop thorugh paths
    with open(path,'rb') as file :#Open file
        data = file.read() #Read contant
        name = path.split("\\")[-1] #Ugly way

    meg.add_attachment(data,maintype = 'application',
                        subtype = 'octet-stream',
                        filename = name) #add file

with smtplib.SMTP_SSL('smtp.gmail.com', 465) as smtp:
    smtp.login(EMAIL, PASSWORD)
    smtp.send_message(msg)
